name: task

on:
  workflow_dispatch:
  schedule:
     - cron: '0 0-16,21-23 * * *'
     - cron: '30 0-3 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
     - name: setup SSH keys and known_hosts
       run: |
           mkdir -p ~/.ssh
           ssh-keyscan github.com >> ~/.ssh/known_hosts
           ssh-agent -a $SSH_AUTH_SOCK > /dev/null
           ssh-add - <<< "${{ secrets.ID_RSA }}"
       env:
           SSH_AUTH_SOCK: /tmp/ssh_agent.sock
     - name: clone repository
       run: git clone git@github.com:zhutou3/green.git ~/js
       env:
           SSH_AUTH_SOCK: /tmp/ssh_agent.sock
     - name: 'Set up Python'
       uses: actions/setup-python@v1
       with:
          python-version: 3.7
     - name: 'Install requests'
       run: |
          cd ~/js
          pip install requests
     - name: 'run task'
       run: |
         cd ~/js   
         python3 task.py
       env:
            YOUTH_HEADER1: ${{ secrets.YOUTH_HEADER4 }}  #必须 账号1 body1
            YOUTH_READBODY1: ${{ secrets.YOUTH_READBODY4 }}  #必须 账号1 body1
            YOUTH_READTIMEBODY1: ${{ secrets.YOUTH_READTIMEBODY4 }}  #必须 账号1 body1
            YOUTH_WITHDRAWBODY1: ${{ secrets.YOUTH_WITHDRAWBODY4 }}  #非必须 账号1提现 body1
            YOUTH_SHAREBODY1: ${{ secrets.YOUTH_SHAREBODY4 }}
            YOUTH_STARTBODY1: ${{ secrets.YOUTH_STARTBODY4 }}
            YOUTH_HEADER2: ${{ secrets.YOUTH_HEADER2 }}
            YOUTH_READBODY2: ${{ secrets.YOUTH_READBODY2 }}
            YOUTH_READTIMEBODY2: ${{ secrets.YOUTH_READTIMEBODY2 }}
            YOUTH_WITHDRAWBODY2: ${{ secrets.YOUTH_WITHDRAWBODY2 }}
            YOUTH_SHAREBODY2: ${{ secrets.YOUTH_SHAREBODY2 }}
            YOUTH_STARTBODY2: ${{ secrets.YOUTH_STARTBODY2 }}
            YOUTH_HEADER3: ${{ secrets.YOUTH_HEADER3 }}
            YOUTH_READBODY3: ${{ secrets.YOUTH_READBODY3 }}
            YOUTH_READTIMEBODY3: ${{ secrets.YOUTH_READTIMEBODY3 }}
            YOUTH_WITHDRAWBODY3: ${{ secrets.YOUTH_WITHDRAWBODY3 }}
            YOUTH_SHAREBODY3: ${{ secrets.YOUTH_SHAREBODY3 }}
            YOUTH_STARTBODY3: ${{ secrets.YOUTH_STARTBODY3 }}
            TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}  #非必须 tg机器人token
            TG_USER_ID: ${{ secrets.TG_USER_ID }}  #非必须 tg机器人userId
