name: test

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
     - name: clone repository
       run: git clone https://github.com/kuIoIo/green.git ~/js
     - name: Use Node.js 14.x
       uses: actions/setup-node@v1
       with:
          node-version: 14.x
     - name: npm install
       run: |
          cd ~/js
          npm install
          npm install cron
          npm install request
          npm install md5-node

     - name: '运行 【test】'
       run: |
         cd ~/js   
         node test1.js
